---
networks:
  npm-net:
    name: npm-net
    driver: bridge

services:
  npm:
    image: 'jc21/nginx-proxy-manager:2.12.3'
    container_name: proxymanager-app
    networks:
      - npm-net
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
      - '81:81'
    environment:
      DB_MYSQL_HOST: "db"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: ${MYSQL_USER}
      DB_MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      DB_MYSQL_NAME: ${MYSQL_DATABASE}
      INITIAL_ADMIN_EMAIL: ${INITIAL_ADMIN_EMAIL}
      INITIAL_ADMIN_PASSWORD: ${INITIAL_ADMIN_PASSWORD}
    volumes:
      - ./npm-data/data:/data
      - ./npm-data/certs:/etc/letsencrypt
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:81 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    labels:
      - "autoheal=true"

  db:
    image: 'jc21/mariadb-aria:10.11.5'
    container_name: proxymanager-db
    networks:
      - npm-net
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./mariadb-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 80s
    labels:
      - "autoheal=true"

  goaccess:
    image: 'xavierh/goaccess-for-nginxproxymanager:v1.1.35'
    container_name: proxymanager-dashboard
    networks:
      - npm-net
    restart: unless-stopped
    ports:
      - '7880:7880'
    environment:
      TZ: America/Argentina/Buenos_Aires
      BASIC_AUTH: ${BASIC_AUTH}
      BASIC_AUTH_USERNAME: ${BASIC_AUTH_USERNAME}
      BASIC_AUTH_PASSWORD: ${BASIC_AUTH_PASSWORD}
      SKIP_ARCHIVED_LOGS: "True"
      PUID: 0
      PGID: 0
      EXCLUDE_IPS: 127.0.0.1
      LOG_TYPE: NPM
      KEEP_LAST: 30 # guarda y muestra 30 dias de data
      PROCESSING_THREADS: 2
    volumes:
      - ./npm-data/data/logs:/opt/log
    depends_on:
      npm:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:7880 || exit 1"]
      interval: 60s
      timeout: 15s
      retries: 3
      start_period: 30s
    labels:
      - "autoheal=true"

  autoheal:
    image: willfarrell/autoheal:latest
    container_name: proxymanager-autoheal
    restart: unless-stopped
    environment:
      - AUTOHEAL_INTERVAL=120
      - AUTOHEAL_START_PERIOD=60
      - AUTOHEAL_DEFAULT_STOP_TIMEOUT=15
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - npm-net
