---
version: '3.7'
networks:
  npm-net:
    name: npm-net
    driver: bridge

services:
  npm:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: npm
    networks:
      - npm-net
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
      - '81:81'
    environment:
      DB_MYSQL_HOST: "db"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: ${MYSQL_USER}
      DB_MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      DB_MYSQL_NAME: ${MYSQL_DATABASE}
    volumes:
      - ./98-themepark-npm:/etc/cont-init.d/99-themepark:ro # chmod +x 98-themepark-npm antes de levantar contenedores
      - ./block-exploits.conf:/etc/nginx/conf.d/include/block-exploits.conf
      - ./npm-data:/data
      - ./npm-data:/etc/letsencrypt
    depends_on:
      - db

  db:
    image: 'jc21/mariadb-aria:latest'
    container_name: db
    networks:
      - npm-net
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./mariadb-data/:/var/lib/mysql

  goaccess:
    image: 'xavierh/goaccess-for-nginxproxymanager:latest'
    container_name: npm-dashboard
    networks:
      - npm-net
    restart: unless-stopped
    ports:
      - '7880:7880'
    environment:
      TZ: America/Argentina/Buenos_Aires
      BASIC_AUTH: ${BASIC_AUTH}
      BASIC_AUTH_USERNAME: ${BASIC_AUTH_USERNAME}
      BASIC_AUTH_PASSWORD: ${BASIC_AUTH_PASSWORD}
    volumes:
      - ./npm-data/logs:/opt/log
    depends_on:
      - npm
  
